### ISSUE TITLE
Some Function Arguments on new lines are listed as not covered

### ISSUE THREAD

**Issue by KaraJ** [keplerproject/luacov#50] opened 2016-08-16 00:05 UTC
When I have a particularly long function call in Lua I usually split it into multiple lines like this:

```
print(
    "thing 1",
    "thing 2"
)
```

When I run the code with luacov some function arguments are shown as no coverage even if the function was called. I have created this simple example.

```
local function print_things()
    print(
        {1,2},
        "hello",
        45
    )
end

print_things()
```

When I run this using `lua -lluacov test.lua` it creates this result:
```
   local function print_things()
 2     print(
 1         {1,2},
 1         "hello",
           45
 1     )
   end

 1 print_things()
```

This seems OK except that the line with just `45` has no coverage data.

When I run this using [busted](https://github.com/Olivine-Labs/busted) with `busted -c test.lua` it creates this result:

```
   local function print_things()
 3     print(
*0         {1,2},
 1         "hello",
           45
 1     )
   end

 2 print_things()
```

This is more of a problem since the `{1,2},` line is showing as not covered when it was clearly called.

I am using:

- busted 2.0.rc12-1
- lucov 0.12.0-1
- lua 5.1.2

**Comment by mpeterv** [comment] 2016-08-16 08:10
The first part is working as intended, the bytecode for loading constant `45` is attached to the next line by Lua compiler, and luacov correctly marks the line as empty. The second one is an issue, but I can't reproduce it. Are you sure busted uses the same lua/luacov version?

**Comment by KaraJ** [comment] 2016-08-16 17:16
There is one thing I had forgotten. I compiled LuaRocks to use LuaJIT so that any rocks installed also use LuaJIT.

I configured LuaRocks using:

```
./configure --lua-suffix=jit --with-lua=/usr
```

When running without LuaJIT the second problem does not occur.

**Comment by mpeterv** [comment] 2016-08-16 18:51
This should be easy to verify by adding `print(package.loaded["luacov.runner"].version, jit and jit.version or _VERSION)` to the test script, it should print luacov and lua versions.

**Comment by KaraJ** [comment] 2016-08-16 18:54
The output is:
```
0.12.0  LuaJIT 2.0.1
```

**Comment by mpeterv** [comment] 2016-08-16 18:55
That's printed when running the script with busted? What about just lua with `-lluacov`?

**Comment by KaraJ** [comment] 2016-08-16 18:57
Yes, that was the output with busted. With `lua -lluacov` I get

```
0.12.0  Lua 5.1
```

**Comment by mpeterv** [comment] 2016-08-16 19:02
I see, LuaJIT must be optimizing the load of a constant array there. I don't think luacov can reliably detect this, can you try installing [cluacov](https://github.com/mpeterv/cluacov)? Just run `luarocks install cluacov` and the run luacov the same way, it will pick it up automatically.

**Comment by KaraJ** [comment] 2016-08-16 19:05
When I run luacov with cluacov installed luacov always seg faults.

**Comment by mpeterv** [comment] 2016-08-16 19:16
Alright. Sorry about that. I can't reproduce it though. Could you open an issue at [cluacov repo](https://github.com/mpeterv/cluacov)? I'll just need to know your OS and maybe compiler version and I'll probably debug it.

**Comment by KaraJ** [comment] 2016-08-16 19:35
OK, I will work on a bug report for cluacov. Thanks for your help.

**Comment by mpeterv** [comment] 2016-10-01 08:28
Closing this as cluacov handles this issue for me. Please open an issue at cluacov repo if you still have the segfault problem.

**Closed by mpeterv** 2016-10-01 08:28 UTC
