### ISSUE TITLE
Breaks with std.lua

### ISSUE THREAD

**Issue by simoncozens** [keplerproject/luacov#37] opened 2015-11-20 11:06 UTC
I have some code which uses the `std` library, and it breaks if `luacov` is loaded before `std`:

    $ lua -e 'require("luacov"); require("std")'
    lua: /usr/local/share/lua/5.2/luacov/runner.lua:101: attempt to call method 'match' (a nil value)

    $ lua -e 'require("std"); require("luacov")'

**Comment by simoncozens** [comment] 2015-11-20 11:22
Here's a minimal case which breaks luacov:

```lua
getmetatable ("").__index = function (s, i)
end

getmetatable ("").__append = function (s, c)
end
```

**Comment by mpeterv** [comment] 2015-11-20 12:05
That luacov breaks when string methods are deleted is not a bug, it's an issue with stdlib that it breaks them. Although I can't reproduce this with the latest version of stdlib (41.2.0-1), maybe you could upgrade?

**Comment by mpeterv** [comment] 2015-11-20 13:04
I've pushed a workaround.

**Comment by hishamhm** [comment] 2015-11-20 18:09
I think in this case the problem is with stdlib, not us. Especially given it's already fixed in their code, we should avoid adding too many workarounds that sort of legitimize the use of bad Lua style for modules.

**Comment by mpeterv** [comment] 2015-11-20 18:18
@hishamhm true, but this issue also comes up in sandboxed loaders (deserializers) that remove string metatable before running untrusted code.

**Closed** 2015-12-07 13:05 UTC
