### ISSUE TITLE
luacov omits break statement in Lua 5.2 and Lua 5.3

### ISSUE THREAD

**Issue by starius** [keplerproject/luacov#26] opened 2015-06-01 22:35 UTC
Lua 5.1:
```
 50     for i = 1, 100 do
 50         if i == 50 then
  1             break
            end
 49         print(i)
        end
```

Lua 5.2:
```
 50     for i = 1, 100 do
 50         if i == 50 then
                break
            end
 49         print(i)
        end
```

**Comment by mpeterv** [comment] 2016-02-16 08:53
This is by design: luacov is not sure whether the line is not hit because it's not covered or because current Lua version doesn't leave a trace for `break`, so it treats it as an empty line. It would be a bug if the line was marked as missed.

**Closed by mpeterv** 2016-02-16 08:53 UTC
